"""
Audit Report API — generates a PDF operational report from current network state.
Uses ReportLab. No external dependencies beyond pyproject.toml.
"""
import io
import time
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.services.prediction import full_risk_report
from app.services.state import get_state

router = APIRouter(prefix="/audit", tags=["audit"])

_RISK_COLOR = {"LOW": colors.green, "ELEVATED": colors.orange, "HIGH": colors.red, "CRITICAL": colors.darkred}


@router.get("/report.pdf")
async def audit_pdf():
    snap = get_state()
    report = full_risk_report(snap)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(Paragraph("MERIDIAN — Operational Audit Report", styles["Title"]))
    story.append(Paragraph(f"Generated: {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}", styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))

    # Network health
    story.append(Paragraph(f"Network Health: {report['network_health']:.0%} — {report['network_level']}", styles["Heading2"]))
    story.append(Paragraph(f"At-risk nodes: {report['at_risk_node_count']}", styles["Normal"]))
    story.append(Spacer(1, 0.3*cm))

    # Corridor risks table
    story.append(Paragraph("Corridor Risk Assessment", styles["Heading2"]))
    cr_data = [["Corridor", "Risk Score", "Level", "Signals"]]
    for r in report["corridor_risks"]:
        cr_data.append([
            r["corridor"],
            f"{r['score']:.2f}",
            r["level"],
            "; ".join(r["signals"][:2]) or "—",
        ])
    tbl = Table(cr_data, colWidths=[3*cm, 2.5*cm, 3*cm, 9*cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 0.3*cm))

    # Node risks table
    story.append(Paragraph("Node Risk Assessment", styles["Heading2"]))
    nr_data = [["Node", "Risk Score", "Level", "Signals"]]
    for r in report["node_risks"]:
        nr_data.append([
            r["node_id"],
            f"{r['score']:.2f}",
            r["level"],
            "; ".join(r["signals"][:2]) or "—",
        ])
    tbl2 = Table(nr_data, colWidths=[4*cm, 2.5*cm, 3*cm, 8*cm])
    tbl2.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
    ]))
    story.append(tbl2)

    # Network nodes summary
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("Network Snapshot", styles["Heading2"]))
    nodes_data = [["Node", "Country", "Type", "Status", "Liquidity (USD)", "Tier"]]
    for node in snap.nodes:
        nodes_data.append([
            node.label,
            node.country,
            node.type,
            node.compliance.status,
            f"${node.liquidity_usd:,.0f}",
            str(node.compliance.tier),
        ])
    tbl3 = Table(nodes_data, colWidths=[4.5*cm, 2*cm, 2*cm, 2.5*cm, 3.5*cm, 1.5*cm])
    tbl3.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
    ]))
    story.append(tbl3)

    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph("This report is generated by Meridian's automated compliance intelligence layer.", styles["Italic"]))

    doc.build(story)
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=meridian_audit.pdf"})
